USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE dbt_wh WITH warehouse_size='x-small';
CREATE DATABASE IF NOT EXISTS dbt_db;
CREATE ROLE IF NOT EXISTS dbt_role;

SHOW GRANTS ON WAREHOUSE dbt_wh;

SHOW USERS;
GRANT ROLE dbt_role TO USER JAYESHHHSF25;
GRANT USAGE ON WAREHOUSE dbt_wh TO ROLE dbt_role;
GRANT ALL ON DATABASE dbt_db TO ROLE dbt_role;

USE ROLE dbt_role;

CREATE SCHEMA IF NOT EXISTS dbt_db.dbt_schema;
